
apiVersion: v1
kind: Service
metadata:
  name: island-db
  namespace: island-system
  labels:
    app: island
    component: db
spec:
  type: ClusterIP
  ports:
    - name: port
      port: 3306
      targetPort: 3306
  selector:
    app: island
    component: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: island-db
  namespace: island-system
  labels:
    app: island
    component: db
spec:
  replicas: 1
  template:
    metadata:
      name: island-db
      labels:
        app: island
        component: db
    spec:
      containers:
        - name: island-db
          image: harbor1.zlibs.com/dockerhub/mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/
              name: conf
      volumes:
        - name: conf
          configMap:
            name: island-db
      restartPolicy: Always
      serviceAccountName: crab
  selector:
    matchLabels:
      app: island
      component: db
---
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: island-db
  namespace: island-system
data:
  init.sql: |
    CREATE DATABASE crab;
    USE crab;

    CREATE TABLE `t_app` (
      `pk` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
      `id` varchar(128) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '唯一名称',
      `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '实例状态',
      `name` varchar(128) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '应用名称',
      `version` varchar(128) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '应用版本',
      `configurations` longtext COLLATE utf8mb4_bin NOT NULL COMMENT '应用配置',
      `dependencies` longtext COLLATE utf8mb4_bin NOT NULL COMMENT '应用依赖',
      `manifest` longtext COLLATE utf8mb4_bin NOT NULL COMMENT '应用描述',
      `parameters` longtext CHARACTER SET utf8mb4 NOT NULL COMMENT '配置参数',
      `deployment` longtext CHARACTER SET utf8mb4 NOT NULL COMMENT '应用部署',
      `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
      `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
      PRIMARY KEY (`pk`) USING BTREE
    ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

    CREATE TABLE `t_status` (
      `pk` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
      `id` varchar(128) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '实例主键',
      `component` varchar(128) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '组件名称',
      `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '组件状态',
      `message` longtext CHARACTER SET utf8mb4 NOT NULL COMMENT '应用部署',
      `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
      `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
      PRIMARY KEY (`pk`) USING BTREE
    ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;